# For use with minikube with enabled ingress.

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: livenessvsreadiness
  labels:
    app: app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: livenessvsreadiness
  template:
    metadata:
      labels:
        app: livenessvsreadiness
    spec:
      containers:
        - name: lvs
          image: rafaelostertag/livenessvsreadiness:latest
          ports:
              - name: http
                containerPort: 8080
          livenessProbe:
            httpGet:
              path: /liveness
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 3
            failureThreshold: 1
          readinessProbe:
            httpGet:
              path: /readiness
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 3
            failureThreshold: 1
---

apiVersion: v1
kind: Service
metadata:
  name: lvs
spec:
  selector:
    app: livenessvsreadiness
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: lvs
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: livenessvsreadiness.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: lvs
              servicePort: 80